apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "fumen.certificateName" . }}
{{- $coveredDomains := dict }}
spec:
  secretName: {{ include "fumen.certificateSecretName" . }}
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: {{ include "fumen.issuerName" . }}
    kind: Issuer
  dnsNames:
{{- range $domain := list .Values.frontend.ingress.domain .Values.backend.ingress.domain }}
  {{- if and $domain (not (hasKey $coveredDomains $domain)) }}
    - "{{ $domain }}"
    {{- $_ := set $coveredDomains $domain true }}
  {{- end }}
{{- end }}
