apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fumen.backend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fumen.name" . }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fumen.name" . }}
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fumen.name" . }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: soundfonts
          image: ghcr.io/sygmei/fumen-soundfonts:{{ .Values.backend.soundfonts.version }}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          command:
            - /bin/sh
            - -c
            - cp -a /opt/soundfonts/. /mnt/soundfonts/
          volumeMounts:
            - name: soundfonts
              mountPath: /mnt/soundfonts
      containers:
        - name: backend
          image: ghcr.io/sygmei/fumen-backend:{{ .Values.backend.version }}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          resources:
            requests:
              cpu: "1"
              memory: 2Gi
            limits:
              cpu: "2"
              memory: 4Gi
          env:
            - name: BIND_ADDRESS
              value: 0.0.0.0:3000
            - name: APP_BASE_URL
              value: https://{{ .Values.frontend.ingress.domain }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: connection-string
            - name: DATABASE_URL_ADMIN
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: connection-string-admin
            - name: DATABASE_URL_READ_ONLY
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: connection-string-ro
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: bucket-name
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: access-key-id
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: secret-key
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: region-name
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: endpoint-url
            - name: SOUNDFONT_DIR
              value: /opt/soundfonts
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          volumeMounts:
            - name: data
              mountPath: /data
            - name: soundfonts
              mountPath: /opt/soundfonts
              readOnly: true
      volumes:
        - name: data
          emptyDir: {}
        - name: soundfonts
          emptyDir: {}
