backend:
  version: "0.2.6"
  replicas: 1
  ingress:
    domain: "fumen-api.lehang.art"
  soundfonts:
    image: "ghcr.io/sygmei/fumen-soundfonts"
    version: "1.1.0"

frontend:
  version: "0.2.6"
  ingress:
    domain: "fumen.lehang.art"
